# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: r
sudo: required
warnings_are_errors: false
bioc_required: true

env:
  global:
    - CRAN: http://cran.rstudio.com

r_packages:
  - covr

bioc_packages:
  - Biostrings
  - seqLogo

after_success:
  - Rscript -e 'covr::codecov()'
